# Generated by Django 4.1.5 on 2023-01-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_notes_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='color',
        ),
    ]
