# Generated by Django 4.1.5 on 2023-01-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_labels_notes_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='font',
        ),
    ]
